2015.09.05  22:20:17 INFO 
		Start crawling proxyips:
2015.09.05  22:20:17 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:20:18 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.115443
2015.09.05  22:20:18 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.236784
2015.09.05  22:20:18 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.447044
2015.09.05  22:20:18 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.903131
2015.09.05  22:20:18 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:20:19 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:1.067599
2015.09.05  22:20:19 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.899860
2015.09.05  22:20:19 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:23:55 INFO 
		Start crawling proxyips:
2015.09.05  22:23:55 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.089372
2015.09.05  22:23:55 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.262422
2015.09.05  22:23:55 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.373853
2015.09.05  22:23:56 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.197455
2015.09.05  22:23:56 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:23:57 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.943602
2015.09.05  22:23:57 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:23:57 INFO 
		Cawled http://cn-proxy.com/ failed.
2015.09.05  22:23:57 ERROR 
		''
Traceback (most recent call last):
  File "proxyip_spider.py", line 65, in request_url
    content = urllib2.urlopen(req, timeout = 10).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
2015.09.05  22:23:57 ERROR 
		must be string or buffer, not None
Traceback (most recent call last):
  File "proxyip_spider.py", line 126, in request_three
    content_str = gzip.GzipFile(fileobj=StringIO(content_gzip), mode="r")
TypeError: must be string or buffer, not None
2015.09.05  22:23:57 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:2.350885
2015.09.05  22:24:05 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:24:06 INFO 
		Cawled http://cn-proxy.com/.
Using time:8.760311
2015.09.05  22:24:06 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:07 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.414645
2015.09.05  22:24:07 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:08 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.863665
2015.09.05  22:24:08 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:18 INFO 
		Cawled http://cn-proxy.com/.
Using time:9.608767
2015.09.05  22:24:18 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:19 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.387885
2015.09.05  22:24:19 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:20 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.902982
2015.09.05  22:24:20 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:21 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.878278
2015.09.05  22:24:21 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:46 INFO 
		Start crawling proxyips:
2015.09.05  22:24:46 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.089172
2015.09.05  22:24:46 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.357577
2015.09.05  22:24:46 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.379870
2015.09.05  22:24:47 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.710197
2015.09.05  22:24:49 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.739727
2015.09.05  22:24:49 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:24:56 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:24:59 INFO 
		Cawled http://cn-proxy.com/ failed.
2015.09.05  22:24:59 ERROR 
		timed out
Traceback (most recent call last):
  File "proxyip_spider.py", line 65, in request_url
    content = urllib2.urlopen(req, timeout = 10).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
2015.09.05  22:24:59 ERROR 
		must be string or buffer, not None
Traceback (most recent call last):
  File "proxyip_spider.py", line 126, in request_three
    content_str = gzip.GzipFile(fileobj=StringIO(content_gzip), mode="r")
TypeError: must be string or buffer, not None
2015.09.05  22:26:23 INFO 
		Start crawling proxyips:
2015.09.05  22:26:23 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087759
2015.09.05  22:26:23 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.253622
2015.09.05  22:26:23 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.419819
2015.09.05  22:26:24 INFO 
		Cawled http://www.haodailiip.com/.
Using time:1.021691
2015.09.05  22:26:33 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:26:33 INFO 
		Cawled http://cn-proxy.com/ failed.
2015.09.05  22:26:33 ERROR 
		timed out
Traceback (most recent call last):
  File "proxyip_spider.py", line 65, in request_url
    content = urllib2.urlopen(req, timeout = 10).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
2015.09.05  22:26:33 ERROR 
		must be string or buffer, not None
Traceback (most recent call last):
  File "proxyip_spider.py", line 126, in request_three
    content_str = gzip.GzipFile(fileobj=StringIO(content_gzip), mode="r")
TypeError: must be string or buffer, not None
2015.09.05  22:27:19 INFO 
		Start crawling proxyips:
2015.09.05  22:27:19 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.086386
2015.09.05  22:27:20 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.262842
2015.09.05  22:27:20 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.421058
2015.09.05  22:27:20 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.713267
2015.09.05  22:27:29 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:27:53 INFO 
		Start crawling proxyips:
2015.09.05  22:27:53 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.086076
2015.09.05  22:27:53 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.314199
2015.09.05  22:27:53 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.358945
2015.09.05  22:27:53 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.420742
2015.09.05  22:27:55 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.079319
2015.09.05  22:27:55 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:27:56 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.060249
2015.09.05  22:27:56 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:01 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.423194
2015.09.05  22:28:01 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:33 INFO 
		Start crawling proxyips:
2015.09.05  22:28:33 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.089498
2015.09.05  22:28:33 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.294049
2015.09.05  22:28:33 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.386289
2015.09.05  22:28:33 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.421136
2015.09.05  22:28:43 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:28:43 INFO 
		Cawled http://cn-proxy.com/ failed.
2015.09.05  22:28:43 ERROR 
		timed out
Traceback (most recent call last):
  File "proxyip_spider.py", line 65, in request_url
    content = urllib2.urlopen(req, timeout = 10).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
2015.09.05  22:28:43 ERROR 
		must be string or buffer, not None
Traceback (most recent call last):
  File "proxyip_spider.py", line 126, in request_three
    content_str = gzip.GzipFile(fileobj=StringIO(content_gzip), mode="r")
TypeError: must be string or buffer, not None
2015.09.05  22:28:44 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.467041
2015.09.05  22:28:44 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:45 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.151448
2015.09.05  22:28:45 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:48 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.383614
2015.09.05  22:28:48 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:49 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.125257
2015.09.05  22:28:49 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:50 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.287088
2015.09.05  22:28:50 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:51 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.150430
2015.09.05  22:28:51 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:52 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.934179
2015.09.05  22:28:52 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:53 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.070452
2015.09.05  22:28:53 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:55 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.213322
2015.09.05  22:28:55 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:55 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.863978
2015.09.05  22:28:55 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:56 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.927868
2015.09.05  22:28:56 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:57 INFO 
		Checked 99 ips. 33 is available.
2015.09.05  22:28:57 INFO 
		Save proxyiprank record to ./proxyiprank.record.json
2015.09.05  22:28:57 INFO 
		Save available proxyips to ./proxyiprank.availability.json
2015.09.05  22:28:58 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.318088
2015.09.05  22:28:58 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:28:59 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.870999
2015.09.05  22:28:59 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:29:01 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.127554
2015.09.05  22:29:01 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:29:02 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.465254
2015.09.05  22:29:02 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:37:22 INFO 
		Start crawling proxyips:
2015.09.05  22:37:22 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.090090
2015.09.05  22:37:22 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.421147
2015.09.05  22:37:22 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.439169
2015.09.05  22:37:22 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.501568
2015.09.05  22:37:28 INFO 
		Cawled http://cn-proxy.com/.
Using time:6.631163
2015.09.05  22:37:28 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:37:32 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:38:11 INFO 
		Start crawling proxyips:
2015.09.05  22:38:11 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.089520
2015.09.05  22:38:11 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.244811
2015.09.05  22:38:11 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.420769
2015.09.05  22:38:12 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.975485
2015.09.05  22:38:12 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:14 INFO 
		Cawled http://www.haodailiip.com/.
Using time:2.915888
2015.09.05  22:38:16 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.433031
2015.09.05  22:38:16 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:18 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.147152
2015.09.05  22:38:18 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:21 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:38:23 INFO 
		Cawled http://cn-proxy.com/.
Using time:5.019132
2015.09.05  22:38:23 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:24 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.348889
2015.09.05  22:38:24 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:29 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.995920
2015.09.05  22:38:29 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:30 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.880236
2015.09.05  22:38:30 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:31 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.088556
2015.09.05  22:38:31 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:32 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.165757
2015.09.05  22:38:32 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:38 INFO 
		Cawled http://cn-proxy.com/.
Using time:5.486651
2015.09.05  22:38:38 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:38:42 INFO 
		Checked 127 ips. 52 is available.
2015.09.05  22:38:42 INFO 
		Save proxyiprank record to ./proxyiprank.record.json
2015.09.05  22:40:01 INFO 
		Start crawling proxyips:
2015.09.05  22:40:01 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.088730
2015.09.05  22:40:01 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.377759
2015.09.05  22:40:01 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.420751
2015.09.05  22:40:01 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.449719
2015.09.05  22:40:02 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.957456
2015.09.05  22:40:02 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:03 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.293495
2015.09.05  22:40:03 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:05 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.236282
2015.09.05  22:40:05 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:11 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:40:13 INFO 
		Cawled http://cn-proxy.com/.
Using time:8.576982
2015.09.05  22:40:13 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:14 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.259775
2015.09.05  22:40:14 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:16 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.120112
2015.09.05  22:40:16 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:17 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.128018
2015.09.05  22:40:17 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:18 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.122032
2015.09.05  22:40:18 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:21 INFO 
		Cawled http://cn-proxy.com/.
Using time:3.331902
2015.09.05  22:40:21 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:22 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.960150
2015.09.05  22:40:22 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:26 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.115344
2015.09.05  22:40:26 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:40:29 INFO 
		Checked 125 ips. 47 is available.
2015.09.05  22:40:29 INFO 
		Save proxyiprank record to ./proxyiprank.record.json
2015.09.05  22:40:29 INFO 
		Save available proxyips to ./proxyiprank.availability.json
2015.09.05  22:40:33 INFO 
		Cawled http://cn-proxy.com/.
Using time:6.434467
2015.09.05  22:40:33 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:23 INFO 
		Start crawling proxyips:
2015.09.05  22:41:24 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086979
2015.09.05  22:41:24 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.181323
2015.09.05  22:41:24 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.240326
2015.09.05  22:41:24 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.419034
2015.09.05  22:41:26 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.776798
2015.09.05  22:41:26 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:31 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.573129
2015.09.05  22:41:31 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:32 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.169656
2015.09.05  22:41:32 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:33 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:41:35 INFO 
		Cawled http://cn-proxy.com/.
Using time:3.202528
2015.09.05  22:41:35 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:41 INFO 
		Cawled http://cn-proxy.com/.
Using time:6.315428
2015.09.05  22:41:42 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:43 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.202653
2015.09.05  22:41:43 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:43 INFO 
		Accept client: 10.15.13.134
2015.09.05  22:41:43 INFO 
		Send successful
2015.09.05  22:41:50 INFO 
		Cawled http://cn-proxy.com/.
Using time:7.044149
2015.09.05  22:41:50 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:51 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.942056
2015.09.05  22:41:51 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:52 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.181697
2015.09.05  22:41:52 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:54 INFO 
		Checked 128 ips. 48 is available.
2015.09.05  22:41:54 INFO 
		Save proxyiprank record to ./proxyiprank.record.json
2015.09.05  22:41:54 INFO 
		Save available proxyips to ./proxyiprank.availability.json
2015.09.05  22:41:55 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.592008
2015.09.05  22:41:55 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:56 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.189986
2015.09.05  22:41:56 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:41:58 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.893947
2015.09.05  22:41:58 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:00 INFO 
		Accept client: 10.15.13.134
2015.09.05  22:42:00 INFO 
		Send successful
2015.09.05  22:42:17 INFO 
		Cawled http://cn-proxy.com/ failed.
2015.09.05  22:42:17 ERROR 
		timed out
Traceback (most recent call last):
  File "proxyip_spider.py", line 65, in request_url
    content = urllib2.urlopen(req, timeout = 10).read()
  File "/usr/local/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/local/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/local/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
timeout: timed out
2015.09.05  22:42:17 ERROR 
		must be string or buffer, not None
Traceback (most recent call last):
  File "proxyip_spider.py", line 126, in request_three
    content_str = gzip.GzipFile(fileobj=StringIO(content_gzip), mode="r")
TypeError: must be string or buffer, not None
2015.09.05  22:42:27 INFO 
		Cawled http://cn-proxy.com/ failed.
2015.09.05  22:42:27 ERROR 
		timed out
Traceback (most recent call last):
  File "proxyip_spider.py", line 65, in request_url
    content = urllib2.urlopen(req, timeout = 10).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
2015.09.05  22:42:27 ERROR 
		must be string or buffer, not None
Traceback (most recent call last):
  File "proxyip_spider.py", line 126, in request_three
    content_str = gzip.GzipFile(fileobj=StringIO(content_gzip), mode="r")
TypeError: must be string or buffer, not None
2015.09.05  22:42:28 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.930571
2015.09.05  22:42:28 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:29 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.944538
2015.09.05  22:42:29 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:30 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.194533
2015.09.05  22:42:30 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:34 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.081682
2015.09.05  22:42:34 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:36 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.993181
2015.09.05  22:42:36 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:38 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.957865
2015.09.05  22:42:38 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:39 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.859996
2015.09.05  22:42:39 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:42:41 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.223068
2015.09.05  22:42:41 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:09 INFO 
		Start crawling proxyips:
2015.09.05  22:44:09 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.088535
2015.09.05  22:44:10 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.231956
2015.09.05  22:44:10 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.246329
2015.09.05  22:44:10 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.420148
2015.09.05  22:44:10 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.899287
2015.09.05  22:44:10 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:12 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.268593
2015.09.05  22:44:12 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:13 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087429
2015.09.05  22:44:13 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.225217
2015.09.05  22:44:13 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:13 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.251915
2015.09.05  22:44:13 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.247743
2015.09.05  22:44:13 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.088873
2015.09.05  22:44:14 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.157581
2015.09.05  22:44:14 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:15 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.953992
2015.09.05  22:44:15 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:16 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087124
2015.09.05  22:44:16 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.911344
2015.09.05  22:44:16 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:16 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087497
2015.09.05  22:44:16 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.182087
2015.09.05  22:44:16 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.407024
2015.09.05  22:44:17 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.135927
2015.09.05  22:44:17 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:19 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.089159
2015.09.05  22:44:19 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.847177
2015.09.05  22:44:19 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:19 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.086092
2015.09.05  22:44:19 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:44:19 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.342304
2015.09.05  22:44:20 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.248006
2015.09.05  22:44:20 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.286985
2015.09.05  22:44:20 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:22 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086260
2015.09.05  22:44:22 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.089288
2015.09.05  22:44:23 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.245817
2015.09.05  22:44:23 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.528414
2015.09.05  22:44:23 INFO 
		Cawled http://cn-proxy.com/.
Using time:3.009239
2015.09.05  22:44:23 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:24 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.843435
2015.09.05  22:44:24 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:25 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087399
2015.09.05  22:44:25 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.073705
2015.09.05  22:44:25 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:25 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.088790
2015.09.05  22:44:26 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.921510
2015.09.05  22:44:26 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:26 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.247657
2015.09.05  22:44:26 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.184910
2015.09.05  22:44:27 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.008453
2015.09.05  22:44:27 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:28 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.957784
2015.09.05  22:44:28 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:28 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.089044
2015.09.05  22:44:28 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.086284
2015.09.05  22:44:29 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.243910
2015.09.05  22:44:29 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.469025
2015.09.05  22:44:30 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:30 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.525606
2015.09.05  22:44:31 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087912
2015.09.05  22:44:31 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.088986
2015.09.05  22:44:32 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.733602
2015.09.05  22:44:32 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:33 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.236852
2015.09.05  22:44:33 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.239862
2015.09.05  22:44:34 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086064
2015.09.05  22:44:35 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.290357
2015.09.05  22:44:35 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:35 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.089578
2015.09.05  22:44:36 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.978504
2015.09.05  22:44:36 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:36 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.255379
2015.09.05  22:44:37 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087346
2015.09.05  22:44:37 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.930235
2015.09.05  22:44:37 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:38 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087279
2015.09.05  22:44:38 INFO 
		Cawled http://www.haodailiip.com/.
Using time:2.151536
2015.09.05  22:44:39 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.542938
2015.09.05  22:44:39 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:39 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.243036
2015.09.05  22:44:40 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.085959
2015.09.05  22:44:41 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087406
2015.09.05  22:44:41 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.071627
2015.09.05  22:44:41 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:41 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.177284
2015.09.05  22:44:42 INFO 
		Checked 132 ips. 57 is available.
2015.09.05  22:44:42 INFO 
		Save proxyiprank record to ./proxyiprank.record.json
2015.09.05  22:44:42 INFO 
		Save available proxyips to ./proxyiprank.availability.json
2015.09.05  22:44:42 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.123046
2015.09.05  22:44:42 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:42 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.252525
2015.09.05  22:44:44 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087982
2015.09.05  22:44:44 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.289536
2015.09.05  22:44:45 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:44:45 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.779402
2015.09.05  22:44:47 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.998507
2015.09.05  22:44:47 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:47 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.876028
2015.09.05  22:44:49 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:2.007051
2015.09.05  22:44:49 INFO 
		Cawled http://www.haodailiip.com/.
Using time:1.013238
2015.09.05  22:44:49 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.986963
2015.09.05  22:44:49 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:49 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:3.940188
2015.09.05  22:44:51 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087753
2015.09.05  22:44:51 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.549582
2015.09.05  22:44:51 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:52 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.088994
2015.09.05  22:44:52 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.168244
2015.09.05  22:44:53 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.597697
2015.09.05  22:44:53 INFO 
		Cawled http://cn-proxy.com/.
Using time:2.582366
2015.09.05  22:44:53 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:54 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086047
2015.09.05  22:44:55 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087703
2015.09.05  22:44:55 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.934294
2015.09.05  22:44:55 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:57 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.223021
2015.09.05  22:44:57 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:44:57 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.089395
2015.09.05  22:44:57 INFO 
		Cawled http://www.haodailiip.com/.
Using time:1.512554
2015.09.05  22:44:57 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:1.141292
2015.09.05  22:44:58 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.089225
2015.09.05  22:45:00 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087503
2015.09.05  22:45:00 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.493619
2015.09.05  22:45:01 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:1.319310
2015.09.05  22:45:02 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.183668
2015.09.05  22:45:03 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.088927
2015.09.05  22:45:04 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.370379
2015.09.05  22:45:04 INFO 
		Cawled http://cn-proxy.com/.
Using time:7.536049
2015.09.05  22:45:04 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:05 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.088958
2015.09.05  22:45:05 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.245267
2015.09.05  22:45:06 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.586987
2015.09.05  22:45:06 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:06 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.381558
2015.09.05  22:45:08 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.088881
2015.09.05  22:45:08 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.247396
2015.09.05  22:45:09 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087441
2015.09.05  22:45:11 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.089493
2015.09.05  22:45:11 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.243086
2015.09.05  22:45:12 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.085931
2015.09.05  22:45:14 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087982
2015.09.05  22:45:15 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.663350
2015.09.05  22:45:15 INFO 
		Cawled http://www.haodailiip.com/.
Using time:8.239205
2015.09.05  22:45:15 INFO 
		Cawled http://cn-proxy.com/.
Using time:9.628994
2015.09.05  22:45:15 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:16 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.085800
2015.09.05  22:45:16 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.919687
2015.09.05  22:45:16 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:17 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087813
2015.09.05  22:45:18 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.371552
2015.09.05  22:45:18 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:18 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.241707
2015.09.05  22:45:19 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.636980
2015.09.05  22:45:19 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.089471
2015.09.05  22:45:19 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.277081
2015.09.05  22:45:19 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:20 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.921530
2015.09.05  22:45:20 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:20 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087697
2015.09.05  22:45:22 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087283
2015.09.05  22:45:22 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.663092
2015.09.05  22:45:22 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.213909
2015.09.05  22:45:23 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.085873
2015.09.05  22:45:24 INFO 
		Cawled http://cn-proxy.com/.
Using time:4.105821
2015.09.05  22:45:24 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:25 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087334
2015.09.05  22:45:25 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.177913
2015.09.05  22:45:25 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.610644
2015.09.05  22:45:26 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.085943
2015.09.05  22:45:28 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086056
2015.09.05  22:45:29 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.251614
2015.09.05  22:45:29 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.884313
2015.09.05  22:45:29 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087680
2015.09.05  22:45:31 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087587
2015.09.05  22:45:32 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.589738
2015.09.05  22:45:33 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087570
2015.09.05  22:45:33 INFO 
		Cawled http://cn-proxy.com/.
Using time:8.795499
2015.09.05  22:45:33 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:33 INFO 
		Cawled http://www.haodailiip.com/.
Using time:1.531460
2015.09.05  22:45:34 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.969111
2015.09.05  22:45:34 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:34 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.101920
2015.09.05  22:45:35 INFO 
		Cawled http://cn-proxy.com/.
Using time:1.100495
2015.09.05  22:45:35 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:36 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.305279
2015.09.05  22:45:36 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.085760
2015.09.05  22:45:36 INFO 
		Cawled http://cn-proxy.com/.
Using time:0.923394
2015.09.05  22:45:36 ERROR 
		list index out of range
Traceback (most recent call last):
  File "proxyip_spider.py", line 138, in request_three
    proxyip_set.add(proxyip[0] + ':' + proxyport[0])
IndexError: list index out of range
2015.09.05  22:45:37 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086386
2015.09.05  22:45:38 INFO 
		Cawled http://www.haodailiip.com/.
Using time:1.441688
2015.09.05  22:45:39 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087907
2015.09.05  22:45:39 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.254472
2015.09.05  22:45:40 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086077
2015.09.05  22:45:42 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087487
2015.09.05  22:45:42 INFO 
		Cawled http://www.haodailiip.com/.
Using time:1.073689
2015.09.05  22:45:42 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.631383
2015.09.05  22:45:43 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.086146
2015.09.05  22:45:45 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.089063
2015.09.05  22:45:46 INFO 
		Cawled http://www.haodailiip.com/.
Using time:0.677802
2015.09.05  22:45:46 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.244037
2015.09.05  22:45:46 INFO 
		Cawled http://cn-proxy.com/ failed.
2015.09.05  22:45:46 ERROR 
		timed out
Traceback (most recent call last):
  File "proxyip_spider.py", line 65, in request_url
    content = urllib2.urlopen(req, timeout = 10).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
2015.09.05  22:45:46 ERROR 
		must be string or buffer, not None
Traceback (most recent call last):
  File "proxyip_spider.py", line 126, in request_three
    content_str = gzip.GzipFile(fileobj=StringIO(content_gzip), mode="r")
TypeError: must be string or buffer, not None
2015.09.05  22:45:47 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087548
2015.09.05  22:45:47 INFO 
		Checked 134 ips. 34 is available.
2015.09.05  22:45:47 INFO 
		Save proxyiprank record to ./proxyiprank.record.json
2015.09.05  22:45:47 INFO 
		Save available proxyips to ./proxyiprank.availability.json
2015.09.05  22:45:48 INFO 
		Cawled http://www.kuaidaili.com/free/inha/.
Using time:0.087580
2015.09.05  22:45:49 INFO 
		Cawled http://ip.izmoney.com/search/china/high/index.html.
Using time:0.253625
2015.09.05  22:45:50 INFO 
		Cawled http://www.kuaidaili.com/free/outha/.
Using time:0.087312
2015.09.05  22:45:50 INFO 
		Start proxyip rank, init ProxyIPRank object
2015.09.05  22:45:50 INFO 
		Cawled http://www.haodailiip.com/.
Using time:1.272228
